export const
  CREATE_SHIPMENT: string = 'CREATE_SHIPMENT',
  CREATE_SHIPMENT_ASYNC: string = `${CREATE_SHIPMENT}_ASYNC`,
  SET_SHIPMENT_VALUES: string = 'SET_SHIPMENT_VALUES',
  SET_DESTINY_VALUES: string = 'SET_DESTINY_VALUES',
  SET_SIZES_VALUES: string = 'SET_SIZES_VALUES',
  SET_SELLER_VALUES: string = 'SET_SELLER_VALUES',
  SET_COURIER_VALUES: string = 'SET_COURIER_VALUES',
  SET_INSURANCE_VALUES: string = 'SET_INSURANCE_VALUES',
  CLEAR_SHIPMENT_FORM: string = 'CLEAR_FORM'
